export const items = [
  "[The Master Sword]",
  "a [Burst Assault Rifle]",
  "a [Sniper Rifle]",
  "a [Grenade]",
  "a [Pistol]",
  "a [Pump Shotgun]",
  "a [Rocket Launcher]",
  "a [Tactical Shotgun]",
  "a [Submachine Gun]",
  "a [Spear]",
  "a [Longbow]",
  "a [Sword]",
  "a [Towel]",
  "a [Crowbar]",
  "a [Damage Trap]",
  "a [Fishing Pole]",
  "a [Banana Bomb]",
  "a [Baseball Bat]",
  "a [Holy Hand-Grenade]",
  "a [Railgun]",
  "a [Super Sheep]",
  "a [Homing Missile]",
  "an [Assault Rifle]",
  "the [Corrupted Ashbringer]",
  "the [Warglaives of Azzinoth]",
  "their [Bear Fists]",
  "their superior wit"
];
